matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
      - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  - pyspelling.filters.url:
  sources:
  - '**/*.md|!**/externalPosts/*|!README.md'
  # - 'src/(!externalPosts|**))/**/*.md'
  # - '**/*.md|!(externalPosts/**/*|README.md)'
  default_encoding: utf-8